version: "3.4"

services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: threads

volumes:
  postgres_data: # Corrected the volume name here

#  postgres:
# image: postgres
# restart: always
# ports:
#   - '5432:5432'
# volumes:
#   - postgres:/var/lib/postgresql/data
#   # To use a local directory instead:
#   # - ./postgres:/var/lib/postgresql/data
# environment:
#   POSTGRES_PASSWORD: docker
#   POSTGRES_DB: gameduels
